version: '3.7'

services:
  front-end:
    image:  ${DOCKER_REGISTRY-}front-end
    container_name: front-end
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - airlinebookingsystem_my-network
networks:
  airlinebookingsystem_my-network:
    external: true
