version: '3.7'

services:

  sample:
    container_name: front-end
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/client'
      - '/client/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - airlinebookingsystem_my-network
networks:
  airlinebookingsystem_my-network:
    external: true
